DELETE FROM pregunta;
DELETE FROM rol;
DELETE FROM usuario;


INSERT INTO pregunta
    (contenido)
VALUES
('¿Qué expectativas tenés para el año que viene?'),
('¿En qué cosa nueva querés invertir tu tiempo?'),
('¿Qué le contas a otros de tu lugar de trabajo?'),
('¿Qué buscás en PNT?'),
('¿Que querés aprender hoy?'),
('¿En qué fallaste hoy?'),
('¿Para qué usamos una arquitectura de 3 capas?'),
('¿Por qué estás en tu equipo?'),
('¿Cómo sería tu vida si no fueses desarrollador?'),
('¿Qué pregunta te incomoda?'),
('¿Qué fue lo último que leíste?'),
('¿Para qué estás escuchando?'),
('¿Qué te enorgullece de esta semana?'),
('¿Cuál fue la mejor tarjeta que te dieron?'),
('¿Qué está pasando en PNT?'),
('¿Qué estás posponiendo?'),
('¿Qué harías si no tuvieses miedo?'),
('¿Qué te gustaría poder contarle con orgullo a tus nietos?'),
('¿Qué sentís cuando escuchas una burla?'),
('¿Cuál fue la mejor decisión que tomaste esta semana?'),
('¿Cómo usarías la lista de lo que queremos aprender?'),
('¿Decimos todo lo que queremos decir?'),
('¿Qué cosa dejaste mejor que cuando la agarraste hoy?'),
('¿Cambió tu rueda de la vida?'),
('¿Decís todo lo que pensás?'),
('¿Estás dando lo mejor de vos?'),
('¿Pensás todo lo que decís?'),
('¿A quién ayudaste hoy?'),
('¿Qué queres aprender de otro?'),
('¿Qué es verdaderamente importante para vos?'),
('¿Estás haciendo todo lo que querés?'),
('¿Comò sabes si progresaste como equipo?'),
('¿Si aumenta la velocidad progresò el equipo?'),
('¿Si progreso el equipo aumentò la velocidad?'),
('¿Què hacemos con las ideas de la hackathon?'),
('¿Que harias si no existiera internet?'),
('¿Qué hacemos  con las ideas de la hackathon?'),
('¿Que harias si no existiera internet?'),
('¿Que hago con mi palta?'),
('¿Que clase de mundo estoy construyendo?'),
('¿Para que podemos usar este pizarron(donde estaba el backlog de expensas)?'),
('¿Agarrarias tu código en 6 meses?'),
('¿Cuando estás satisfecho con tu código?'),
('¿Que queres lograr con tus conversaciones?'),
('¿Cuál fue el The Core que más te sirvió?'),
('¿Que sos: Reader, Process o Writer?'),
('¿Podes ser los 3?'),
('¿Que cambiaste hoy?'),
('¿Que se van a acordar de vos?'),
('¿Que haces en la semana que tambien haces el finde?'),
('¿Que pasaria si este pizarron no pudiera borrarse?'),
('¿Que te olvidaste de preguntar hoy?'),
('¿Que queja transformaste en acciòn?'),
('¿Que te saca de tu zona de confort?'),
('¿Qué riesgos estás tomando?'),
('¿Cuantos commits te quedan de vida?'),
('¿Como sabès que tu producto generò valor?'),
('¿Què estàs pensando?'),
('¿Que fail te mandaste hoy?'),
('¿Que intentaste hacer distinto?'),
('¿Que le dejaste hoy a tu equipo?'),
('¿Para que te levantaste hoy?'),
('¿Como te vas a divertir hoy?'),
('¿A quien prejuzgaste hoy?'),
('¿Reaccionas o acciones?'),
('¿Que te gusto de hoy?'),
('¿Como empezaste el día?'),
('¿Que soltaste hoy?'),
('¿Estás creciendo?'),
('¿Que prejuicios tenes?'),
('¿Que te gusta de PNT?'),
('¿Que estás aportando?'),
('¿Cómo mejoraste la comunicación en tu equipo?'),
('¿Que conversacion importante tenes pendiente?'),
('¿Que podes enseñarle a los demás?'),
('¿Qué podes aprender de los demás?'),
('¿Qué hacemos con las preguntas?'),
('¿Que preguntas sin respuesta podes hacerte hoy?'),
('¿En que te estas superando?'),
('¿Que pregunta no haces por vergüenza?'),
('¿Cual es tu mejor horario para codear?'),
('¿En que te estas superando?'),
('¿Que error convertiste en aprendizaje?'),
('¿Cuanto tiempo podes estar sin internet?'),
('¿Porque empezar por el por qué?'),
('¿Cómo motivas a tu equipo?'),
('¿Cómo te motivas?'),
('¿Que es lo que más te gusta hacer?'),
('¿Scrum o Kanban?'),
('¿Que te gusta mas de hoy?'),
('¿Como te queres sentir hoy?'),
('¿Qué valores te gustaria trasmitir?'),
('¿Qué valores representan las acciones que tomas hoy?'),
('¿Cómo podemos lograr mejores diseños?'),
('¿Que valores representan las acciones que tomamos hoy?'),
('¿Como podemos lograr mejores diseños?'),
('¿Que espectativas tenes para el año que viene?'),
('¿En qué cosa nueva queres invertir tu tiempo?'),
('¿Que les contas a otros de tu lugar de trabajo?'),
('¿Que ideas te gustaría probar hoy?'),
('¿De quien aprendes?'),
('¿Què ideas te gustaria probar hoy?'),
('¿De quièn aprendes?');


INSERT INTO usuario
    (id,    email,                      password)
VALUES
    (1,     'matzam@gmail.com',         '$2a$10$6bdxXpmewXVY0SiN94aGEeKPcLW0XVrfZENii0ksZgBiTGJrTbgPu');

INSERT INTO rol
    (id_usuario,    rol)
VALUES
    (1,             'ROLE_USER');